version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tuananh
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    networks:
      - nesjs-network
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    environment:
      TYPEORM_HOST: db
    command: npm run start:dev
    ports:
      - 3003:3003
    networks:
      - nesjs-network
    depends_on:
      - db
    
networks:
    nesjs-network:
      driver: bridge